select
'DATALAKE' AS SOURCE,
CONVERT(DATE,CONCAT(RIGHT([PERIOD],2,'/01/'),[FISCAL_YEAR]), 101) AS FISCAL_MONTH,
CASE
WHEN [DESC] = 'Current Accrual' THEN 'ACCRUAL'
WHEN [DESC] = 'Prior Period' THEN 'PPA'
ELSE 'OTHER'
END AS ACCRUAL_TYPE,
CASE
WHEN [HIERARCHY] = 'HWK' THEN 'HAWK'
WHEN [HIERARCHY] = 'Hk' THEN 'HAWK'
ELSE 'NA'
END AS ASSET,
DAY(EOMONTH(CONVERT(DATE,CONCAT(RIGHT([PERIOD],2,'/01/'),[FISCAL_YEAR]), 101)) AS DAYS_IN_MONTH,
CASE
WHEN [ACCOUNT] = '005' and PRODUCT = 'G' THEN TRYCAST(SUM(QUANTITY) AS DECIMAL(38,4))/DAY(EOMONTH(CONVERT(DATE,CONCAT(RIGHT([PERIOD],2,'/01/'),[FISCAL_YEAR]), 101))))/1000
ELSE 0
END AS QUANTITY,
WHEN [ACCOUNT] = '005' and PRODUCT = 'O' THEN TRYCAST(SUM(QUANTITY) AS DECIMAL(18,2))
ELSE 0
END AS  'QUANTITY/DAYS'
from DATALAKE
WHERE PERIOD >='001' AND PERIOD <='012'
GROUP by PERIOD, FISCAL_YEAR, [DESC], [HIERARCHY]
ORDER BY FISCAL_MONTH, ACCRUAL_TYPE, ASSET, DAYS_IN_MONTH
